### PR TITLE
option to skip keyboard if title is forced

### PR DESCRIPTION
**Pull request by fastcolors**
if the argument ?title is used it skips the requests for the tvshow to
add, and searches for the title already chosen.

useful if you pull the tv show from a list presented by another addon

used like this:

RunPlugin(plugin://plugin.video.sickrage?title=$INFO[Container(311).List
Item.Label])

### CODE REVIEW

**Comment by fastcolors** [comment]
PS: if you ever need help with the ui, I made the whole kodi icon pack, so it would be no sweat to do some graphics here. ;)

cheers!!!

**Comment by Hiltronix** [comment]
Good idea.  But an error is introduced as the code stands in addshow.py in function showSearchDialog.

Escaping the keyboard entry dialog creates an uninitialized variable error.  Since you removed the lines:

  else:
    text = ''

Which was required to exit the function and AddShow() cleanly when escaping the keyboard dialog.

**Comment by fastcolors** [comment]
how about we set the variable text @ starting point?

I'm fairly slow when it comes to phyton... forced to learn a little when starting skinning for kodi...

**Comment by fastcolors** [comment]
fixed.

my suggestion would be to abort the operation if keyboard is dismissed...

**Comment by Hiltronix** [comment]
Did you update the code on AddShow.py in your Fork?  I don't see it fixed.

Yes we can set it to nothing at the start of the function, or at the end as I had it when the keyboard is aborted like I had it.  The end result will be the same.  Having "text" empty when the function returns shows that the keyboard was aborted to the function that called it, which would be AddShow.  That way AddShow can exit the AddShow.py script smoothly when the keyboard is aborted.

Lots of coders in a hurry never bother allowing for (or testing for) exiting/escaping at each step in a user interface, which is actually very important.  When I test my own code I always try exiting at each step to make sure things end smoothly without an error.  It's easy to over look. :)

**Comment by fastcolors** [comment]
yep it's fixed in the latest commit up here...

I actually fix it back the way you had it... just adding another if - else at the end

but I do think you should work it in a way that if text is empty, nothing actually happens, instead if you exit at keyboard.. it brings you to an empty search result page, which is an incorrect exiting IMHO...

**Comment by fastcolors** [comment]
https://github.com/fastcolors/plugin.video.sickrage/commit/ad6fdfba2ecb2fa2279f193ecb2cb51e832548fc

**Comment by Hiltronix** [comment]
I don't like that it exits to an empty folder either.  It's a crappy exit.  And for someone less familiar with how Kodi addons work, it will seem confusing.  The problems comes from how these list menus using "addDirectoryItem" work,  They are either a folder or not, using "isFolder".  All other content from our main menu needs to be a folder, but Add New doesn't.  

And I just realized how to fix this.  I will selectively set each AddDirectory item to either be a "folder" or not.  Right now they are all folders, that's where our empty folder on exit comes in.  It even happens after we add a new show exiting normally.  This change I will make will solve that blank empty folder when we exit the script.  

Bare with me with the updates.  I'll commit your changes this weekend, and fix this blank menu issue as well. :)

**Comment by Hiltronix** [comment]
Your SickRage shark icon is def a better quality than what I borrowed from their site.  Looks good.  But could you change the colour of the font please, to something more contrasting.  For example, I'm blue/red colour challenged.  So seeing the dark red font as is, against the blue doesn't stand out well for me and is difficult to read.  What do you think about using a gold for the font, which would also be consistent with the font colour the SickRage project icon uses?  I'm not suggesting their ragged font style, just the contrasting font colour.  Thanks.

**Comment by fastcolors** [comment]
should I remake the PR?

everything is fixed and working... if you're not gonna pull this, I'll just branch out, let me know...

**Comment by Hiltronix** [comment]
Is it possible to remove the image file from the PR?  If not if you could remake the PR.  I have updated the icons with a better cleaner image already.  Sorry for being slow on getting this up.  I only finished adding a repo on github this afternoon.  And was just going to manually add your code changes if I didn't hear back from you, since I don't think I easily merge without adding the image.  Thanks for your patience.

**Comment by Hiltronix** [comment]
Github won't allow an auto merge, so I updated the code manually in v.1.0.4.  Also added busy dialog for the Add New Show in v.1.05, as I noticed if there is a delay in the lookup, the user could think nothing is happening and restart the request.

**Comment by fastcolors** [comment]
Did i check out The Whole icons? I saw you Made a cleaner one, but just have a look at The ones i Made. Then if you still like youra better no problem. Close this pr. In case you want The icons i'll open a new one.

**Comment by Hiltronix** [comment]
We closed this PR, but I wanted to inform you iof a change I made per another user's request in v.1.0.6.

He wanted to be able to add shows based on TVDBid, and suggested (I think) a better API call system that allows for API call structure going forward.  I simply builds on your code changes.  Below is the message I sent him so you can read what I sent him.  I didn't remove the "title" argument that I assume you are now using from another addon.  And I won't if you continue to use it.  But what do you think about this other format, using "action" parameter and then a secondary parameter.  I figured that format makes sense going forward for future API calls.  Maybe "delete" or episode lookup calls, etc.

The brief explanation is in the ChangeLog.

Carey  

---

Take a look at version 1.0.6.  I included the change you requested.  Also see the ChangeLog.  I set up the API request pretty much like you suggested, as well as added the same for show name.

  Examples:
    RunPlugin(plugin://plugin.video.sickrage?action=addshow&tvdb_id=TVDB_ID)
    RunPlugin(plugin://plugin.video.sickrage?action=addshow&show_name=SHOW_NAME)

In the case of the TVDV_ID lookup, it first converts the id code to the TV show name, and it pops up with the show name list prompt, as if you entered the name to search.  So in rare cases where multiple shows have the same name, you'll still have to select it based on date as the SickRage web interface does.  The reason I did it this way was to allow for someone sending a TVDBid that doesn't exist, so it still falls back to the normal user interface and confirmation of the correct show.

I hope that works for you.  Please test it out and let me know.

Carey

**Pull request closed without merging**
