### PR TITLE
added web root to settings for reverse proxy, 

### PR DESCRIPTION
**Pull request by maikito26**
custom url didn't work for me past scraping API. So I added the ability to use the webroot setting.  Also added some default values out of convenience.

### CODE REVIEW

**Comment by Hiltronix** [comment]
Can you give me an example of your url looks like that didn't work when you entered it in custom url?  I'd like to see what doesn't work and why.  I see no point if having two custom methods, or leaving one in that doesn't work properly.  Either custom url should be fixed, or if it's better your way, it needs to be taken out.  But I'd like to understand what's not working in the current code first.

**Comment by maikito26** [comment]
I agree with you.  I didn't take the time to fully look into the custom URL implementation since I didn't look at the full scope of what you were intending.  I know SickBeard/SickRage has the web root config setting which I have taken advantage of.  I can grab the log lines later on when I get back home, but in a nutshell I've got SickRage running at http://127.0.0.1:8083/tv.  When using Custom URL is pulled in the API.  But then the addon would send API calls to SickRage using http://127.0.0.1:8083/api instead of http://127.0.0.1/tv/api, thus not using the custom URL but rather the base URL.  If custom URL was intended to be for the web root config setting then maybe I can relook into where the add-on was using the base url instead of custom url and create a pull request for that.  In my opinion however, since the add-on requires IP and port settings to be config'd anyway, custom URL should just be the web root.

**Comment by Hiltronix** [comment]
Thanks for the details.

The custom URL is actually a hold over from the original author of the 
plugin.  The code has expanded a lot since then, and to be honest I 
haven't tested the custom URL since early on.  I was actually interested 
to see if and when someone would comment on their case use for using the 
custom URL.  Your example is perfect for me to see where this is useful, 
since I personally didn't currently need to use it.  It's likely been 
broken from changes I made and I simply forgot to test it since.

Tomorrow I'll take a look at this and leaning towards your 
implementation.  And if the Custom URL is broken and no one has 
complained, no one is likely currently using it other than you.  So it 
shouldn't be an issue to remove it, if your commit solves custom issues.

However, I disagree with setting the default IP and port.  It was 
intentional on my part.  My reasoning is this; with those fields blank, 
and the user doesn't set them on initial setup, the error messages 
prompt to remind them.  My concern is that novice users and people in a 
hurry see it filled in and leave it, then when it doesn't work properly 
they complain it simply doesn't work.  I'd rather field a support 
message helping someone understand what needs to go in this field, than 
try to help someone figure out why (something obvious to you or I) 
doesn't work.  I use a remote IP, you use the local host, I use port 
8080, you use 8083.  Neither my default or yours will be correct to the 
next user, and the novice installer may be mislead.  Since the plugin 
does check and prompt to fill this in, I think it best to not set the IP 
and port fields with defaults

On 2015-10-12 10:59 AM, maikito26 wrote:

> I agree with you. I didn't take the time to fully look into the custom 
> URL implementation since I didn't look at the full scope of what you 
> were intending. I know SickBeard/SickRage has the web root config 
> setting which I have taken advantage of. I can grab the log lines 
> later on when I get back home, but in a nutshell I've got SickRage 
> running at http://127.0.0.1:8083/tv. When using Custom URL is pulled 
> in the API. But then the addon would send API calls to SickRage using 
> http://127.0.0.1:8083/api instead of http://127.0.0.1/tv/api, thus not 
> using the custom URL but rather the base URL. If custom URL was 
> intended to be for the web root config setting then maybe I can relook 
> into where the add-on was using the base url instead of custom url and 
> create a pull request for that. In my opinion however, since the 
> add-on requires IP and port settings to be config'd anyway, custom URL 
> should just be the web root.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Hiltronix/plugin.video.sickrage/pull/5#issuecomment-147446029.

## 

Hiltronix Computer Services
Winnipeg, Manitoba, Canada

**Comment by maikito26** [comment]
I do agree with all of that.  I think I added it more as a convenience thing.  I know when I was first setting up the add-on from fresh (twice on separate boxes) when I went to configure the port it was presenting the IP Address toast.  Your settings.xml config was set to number so I think it was a Kodi glitch and I had to update the userdata/settings.xml manually in order for it to recognize a number.  I'm not sure why or how this occurred as the only workaround was to set a default port value.  If this isn't happening for you I wouldn't worry about it.  You're also probably more disciplined in programming best practices than I am since I'm only about 1 month into Python coding.

The other thing I would say is that my changes for the pull request doesn't have any string checking.  I hard coded a '/' onto the string.  It might be worth stripping any '/' or '\' from the user inputted data, or checking the strings validity, in the spirit of keeping future novice users from being confused. 

In any case, its a great add-on so thank you for the work.  My wife is especially thankful since she doesn't fully get how to navigate our home network outside of Kodi.

**Comment by Hiltronix** [comment]
Thanks for the compliment.  It's always nice to hear that this plugin is useful to other people as well.

I've committed your changes in v.1.3.13.  And since then I realized an issue with stripping slashes from the webroot, and making it a rule to hard code the prepending slash.  Doing so doesn't allow for a multi-level webroot path.  So in v.1.3.14, you can add a prepending slah or not, the app will add it when required, and remove trailing slashes.  That way multi-level webroot paths can be entered.

When your system(s) update to 1.3.14 it should look after adding the prepending slash when it restarts.  In worse case you may have to go into settings, check the webroot you entered, click OK, and restart the plugin.

**Comment by maikito26** [comment]
Just updated.  Its working/looking great for me without needing to reset my settings.  I am now up to date with this version.

Cheers!

**Comment by Hiltronix** [comment]
Glad to hear it.  Thanks for your feedback and contribution.

**Pull request merged**
