### PR TITLE
Change repo URL

### PR DESCRIPTION
**Pull request by duramato**
Quote from miigotu 
`As a team, we have moved from the old org (SiCKRAGETV) to a new org (SickRage), only leaving echelon behind. New org is nearing 2k commits ahead of the old one and is much more stable and maintained, as well as a much larger user base as users have opted to move with the team.
For questions, we are on freenode in #sickrage-issues`

### CODE REVIEW

**Comment by Hiltronix** [comment]
I won't be updating the links in the addon to this forked version of SickRage.  The links will remain to the original project.  Echel0n has informed me that he is the owner, founder and original coder of SickRage.  And he has apparently taken back control of the SickRage project, and "uninvited" the team that has forked the project under a similar name.

Here is the post that can be seen in the SickRage project under News:

```
!!! IMPORTANT MEMBER ALERT !!!

IT HAS BEEN BROUGHT TO MY ATTENTION FORMER EX-TEAM MEMBERS OF SICKRAGE
ARE SOLICIATING USERS TO SWITCH TO A NEW GITHUB REPO ADDRESS THAT IS IN NO WAY
OFFICIAL OR OWNED BY ME, DOING SO COULD ALLOW THEM TO INFECT YOUR COMPUTER
SYSTEMS WITH MALICAIOUS CODE THAT COULD WIPE YOUR ENTIRE SYSTEM OUT DATA
AND ALL SO PLEASE REPORT ANY FURTHER ABUSE TO SICKRAGE.TV@GMAIL.COM
```

**Comment by labrys** [comment]
@Hiltronix That's your prerogative, but the team that he 'uninvited' is the team that had been doing the work for the last 8+ months.  In addition he was not the 'original coder' of SickRage.  He has also gone to extreme lengths to slander and discredit the team that has worked so hard on the project.

All that aside, the new [SickRage](https://github.com/SickRage/Sickrage) repository has seen many updates, bug fixes, performance enhancements, and new features since the drama and will continue to see more.  While the old repository has had few changes and most of those were reverting old code or introducing new bugs and has lead to a more unstable product.

**Comment by labrys** [comment]
Posted on behalf of @miigotu:

@Hiltronix I think you should read more about what actually happened, maybe come talk to the rest of the community.

echelon came back after a year of MIA, and blew up the whole project. He has taken down all support and issue trackers, plans to charge users for support, etc.

He has done this before, we decided as a team to move after the bs he did with me when he came back, to move to a new org. Not a single person has stayed behind except him, and the old repo is terribly broken.

We are 2k commits ahead, and very stable, with more users than the other repo already.

More developers than there ever were before:
https://github.com/orgs/SickRage/people

The major 3rd parties have switched, including freenas, synology, sickrageinstaller, arch, etc.

SickRage isnt 'owned' as he wants everyone to think. It doesnt belong to him whatsoever. This all started because while he was away for a year doing whatever we weren't passing donations to him, because we wanted to let donators to decide where their money went.

We have all of the text posted publicly of the conversations that happened when this change was made. There is no malicious craziness going on, in the end we simply fired echelon and moved on, so that he could no longer disrupt this OPEN SOURCE project. He had caused a similar issue before that resulted in `SickGear` because he wanted to close the source and charge for it then.

SickRage will remain free and without drama in our repo.

freenode #sickrage-issues

**Comment by Hiltronix** [comment]
Well thanks for all that info.  However, I stopped offering PR's and even updating the project on my own system the last several months, due to me personally feeling the project was often unstable due to errors introduced from code being updated too rapidly, and didn't care for code change decisions that were sometimes made.  And most of all, one of the main devs is rude and has a bad attitude, in my opinion.  It was this person's behavior that caused me to become disinterested in the SickRage project.  So I personally welcome change in the original SickRage project, and for the time being I will look forward to supporting the original SickRage project till I personally feel otherwise.  

I don't care what the drama is or was, and I'm not interested in reading about it.  I'm only interested in supporting projects that are drama free, and more importantly where people are polite and treat each other with respect.  I did not feel that way the past year with many of my interactions with the SickRage project.  Nor did I care for how some other people where responded to by the dev I mentioned earlier either.

I was already seriously considering starting my own similar project, due to my issues with SickRage, that I already mentioned.  So instead, I will wait and see for myself where Echel0n takes SickRage.  If he runs it into the ground, and pisses people off, then you have nothing to worry about, people will simply look for change.  

I'd appreciate not getting any more feedback about this.  I'm entitled to my own opinion, as are you.

**Comment by labrys** [comment]
No problem, and good luck with your project.  Happy holidays :grinning:

**Pull request closed without merging**
