### PR TITLE
new HD icons

### PR DESCRIPTION
**Pull request by fastcolors**
if you need more let me know.

### CODE REVIEW

**Comment by Hiltronix** [comment]
Thanks very much.  I like your icons, they look great.  But I like my icons as well. :)  But I do appreciate your hard work in creating them.  Maybe at some point when there are more people using the icon will have to have some sort of a survey and see what the majority says about which they prefer. :)

BTW, I submitted the addon to the XBMC official repo.  I haven't heard back yet.  I'm curious if they will allow it since it's an interface for a project that some might consider having copyright issues.  While I was researching the rules for submitting addons, I discovered that they won't allow addons with icons with transparent backgrounds.  Which is why I now have a solid colour BG on the icons.  Personally I think some icons look better with transparent BG's, but it turns out the addon moderators refuse them for consistency or something.

Bare in mind if the addon gets accepted into the official repo, we won't be able to use them anyway unless they have a solid background.

Also, as you likely know, replacing icons on XBMC addons doesn't seem to work well, when a user does an update.  XBMC draws from a cache unless lines in the "textures13.db" are removed or updated.  I have yet to discover if there is a way to force icon updates.  Often I have to manually edit "textures13.db" to get this to happen on my local machines.  If you have any insight into the best way to update icons on existing addon installs, please let me know.

**Comment by fastcolors** [comment]
At least make them hi def and remove The watermark. I understand you want full control over this project but i suggest you make objective decisions. As far as graphic design goes you need to clean them out quite a bit. 

Anyhow, good luck with The project.

Cheers.

**Comment by fastcolors** [comment]
Also i have a Skin in official repo and i use transparent background icons. Never heard you need a flat bg...

**Comment by fastcolors** [comment]
But them might have added a Few compatibility rules...

**Comment by Hiltronix** [comment]
Objective decisions?  Really?  You're right, it is my project, and I've 
been very cooperative and polite with you.  You included images without 
asking if I wanted new ones, in a PR with code changes. Those are two 
separate topics.  I was polite about you slipping them in, and even 
explained at length why I haven't included them yet. So actually I take 
some offence to the sour grapes sounding criticism.

I'm doing this project for the fun of it.  I don't need undue criticism, 
attitude, or trolling comments going forward.  And for anyone else 
reading this that might want to collaborate, I'd appreciate the same 
respect, tact, and level of politeness in return as I give to you.

Good day.

**Comment by fastcolors** [comment]
:)

**Comment by fastcolors** [comment]
PS: you're not DOING this, You're just picking this up. ;-)

**Pull request closed without merging**
